package com.serveflow.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Token — represents a food pickup token generated for a customer.
 *
 * Tokens are generated in two scenarios:
 *   Flow A (Campus Bite online order): Generated when a student's Razorpay payment
 *           is confirmed. The student shows this token when collecting food.
 *   Flow B (QuickBill counter bill):   Generated when a counter bill is confirmed
 *           (either cash payment, or a UPI payment is matched to the bill).
 *
 * Token Number:
 *   Sequential, concurrency-safe number (e.g. 1, 2, 3...). Generated by TokenService
 *   using a PESSIMISTIC_WRITE lock on the TokenSequence table.
 *   We do NOT use SELECT MAX(tokenNumber) + 1 because two simultaneous requests
 *   could both read the same MAX value and produce duplicate token numbers.
 *
 * Printing:
 *   After creating a Token, TokenService calls PrinterService.printToken(token).
 *   If the printer is offline, status = PRINT_FAILED and the virtual fallback
 *   renders the token on-screen in the QuickBill Recent Tokens zone.
 *
 * Relationships:
 *   - One-to-one with Bill (for Flow B counter tokens — bill is set, order is null).
 *   - One-to-one with Order (for Flow A online tokens — order is set, bill is null).
 *   Only ONE of bill or order will be non-null for any given token.
 */
@Entity
@Table(name = "tokens")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Token {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Sequential token number displayed to the customer (e.g. 42, 43, 44...).
    // Generated by TokenService using row-level locking — see TokenSequence entity.
    private Long tokenNumber;

    // The counter bill this token was generated for (Flow B).
    // Null for online order tokens (Flow A).
    @OneToOne
    @JoinColumn(name = "bill_id", nullable = true)
    private Bill bill;

    // The online order this token was generated for (Flow A — Campus Bite).
    // Null for counter bill tokens (Flow B).
    @OneToOne
    @JoinColumn(name = "order_id", nullable = true)
    private Order order;

    // Human-readable summary of what was ordered, for display and printing.
    // Example: "Chicken Fried Rice x2" or "Student Combo Meal x1, Coca Cola x2"
    private String itemSummary;

    // Total amount the customer paid — displayed on the token slip.
    @Column(precision = 10, scale = 2)
    private BigDecimal amount;

    // Current print status. See TokenStatus enum.
    // ACTIVE → PRINTED (success) or PRINT_FAILED (printer offline).
    @Enumerated(EnumType.STRING)
    private TokenStatus status;

    // Timestamp when this token was created.
    private LocalDateTime generatedAt;

    // Timestamp when the token was successfully sent to the physical printer.
    // Null if printing has not yet succeeded (ACTIVE or PRINT_FAILED status).
    private LocalDateTime printedAt;
}
